### ISSUE TITLE
Completly Broken

### ISSUE THREAD

**Issue by MrEnder0** [BluCodeGH/bedrock#13]
Windows 10

When I import the module "bedrock" after installing I get the following err.

Warning (from warnings module):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\gensim\utils.py", line 1197
    warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
UserWarning: detected Windows; aliasing chunkize to chunkize_serial
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\fghfhgf.py", line 1, in <module>
    import bedrock
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\bedrock\__init__.py", line 2, in <module>
    from bedrock import *
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\bedrock\process.py", line 3, in <module>
    from bedrock.processors.SpacyProcessor import SpacyProcessor
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\bedrock\processors\SpacyProcessor.py", line 2, in <module>
    import spacy
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python36\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
ImportError: cannot import name 'prefer_gpu'
>>>

It would be nice if this could be fixed because I want to use this in a project.

**Comment by BluCodeGH** [comment]
This library is not on PyPI so you cannot `pip install` it. You've accidentally installed https://pypi.org/project/bedrock instead. To use this library you need to clone the repository.
