### ISSUE TITLE
dlopen failed has unexpected e_machine

### ISSUE THREAD

**Issue by NguyenDuck** [BluCodeGH/bedrock#16]
```
WARNING: linker: dlopen failed: "/usr/lib/python3.10/site-packages/bedrock/libleveldb.so" has unexpected e_machine: 62 (EM_X86_64), targetsdk: 10000, retry
Traceback (most recent call last):
  File "/root/temp.py", line 1, in <module>
    from bedrock import World
  File "/usr/lib/python3.10/site-packages/bedrock/__init__.py", line 1, in <module>
    from .bedrock import World, Chunk, SubChunk, Block, CommandBlock
  File "/usr/lib/python3.10/site-packages/bedrock/bedrock.py", line 6, in <module>
    from . import leveldb as ldb
  File "/usr/lib/python3.10/site-packages/bedrock/leveldb.py", line 13, in <module>
    ldb = ctypes.cdll.LoadLibrary(op.join(op.dirname(op.realpath(__file__)), "libleveldb.so")) # Load DLL
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: "/usr/lib/python3.10/site-packages/bedrock/libleveldb.so" has unexpected e_machine: 62 (EM_X86_64)```

**Comment by BluCodeGH** [comment]
The included leveldb binary is built for an x86_64 python installation, it appears you will need to build your own binaries from https://github.com/Mojang/leveldb-mcpe.
