### ISSUE TITLE
Help wanted; KeyError: 'Chunk at 0, 0 (Dim 0) does not exist.'

### ISSUE THREAD

**Issue by Jan-Egil-G** [BluCodeGH/bedrock#21]
ive downloaded code, ran setup.py. now i try to run the example code, but set commands deleted. Then this code:

  if world.getBlock(4, 4, 3).name == "minecraft:stone":

Gives this output:

raceback (most recent call last):
  File "c:\PyPj\minecraft2\bedrock\bedrock.py", line 120, in _loadVersion
    version = ldb.get(db, self.keyBase + b",")
  File "c:\PyPj\minecraft2\bedrock\leveldb.py", line 168, in get
    raise KeyError("Key {} not found in database.".format(key))
KeyError: "Key b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00,' not found in database."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\PyPj\minecraft2\bedrock\bedrock.py", line 125, in _loadVersion
    version = ldb.get(db, self.keyBase + b"v")
  File "c:\PyPj\minecraft2\bedrock\leveldb.py", line 168, in get
    raise KeyError("Key {} not found in database.".format(key))
KeyError: "Key b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00v' not found in database."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\PyPj\minecraft2\test.py", line 10, in <module>
    if world.getBlock(4, 4, 3).name == "minecraft:stone":
  File "c:\PyPj\minecraft2\bedrock\bedrock.py", line 39, in getBlock
    chunk = self.getChunk(cx, cz, dimension)
  File "c:\PyPj\minecraft2\bedrock\bedrock.py", line 30, in getChunk
    chunk = Chunk(self.db, x, z, dimension)
  File "c:\PyPj\minecraft2\bedrock\bedrock.py", line 98, in __init__
    self.version = self._loadVersion(db)
  File "c:\PyPj\minecraft2\bedrock\bedrock.py", line 132, in _loadVersion
    raise KeyError("Chunk at {}, {} (Dim {}) does not exist.".format(self.x, self.z, self.dimension))
KeyError: 'Chunk at 0, 0 (Dim 0) does not exist.'

**Comment by BluCodeGH** [comment]
This library has not been updated in a long time, so the level storage format may have changed. Do make sure you've actually generated the chunk at 0, 0 though, typically the game will only save chunks after you've made a change to them (eg placed a block).
